// this is for constant action types used in reducers / actions

export const LOGIN_ACTION = "LOGIN_ACTION";
export const CHANGE_USERNAME = "CHANGE_USERNAME";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const WRITE_GROUP_POST_INPUT = "WRITE_GROUP_POST_INPUT"
export const SET_LOGIN_PENDING = "SET_LOGIN_PENDING";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const SET_LOGOUT = "SET_LOGOUT";

export const SET_CREATE_USER_SUCCESS = "SET_CREATE_USER_SUCCESS";
export const SET_CREATE_USER_ERROR = "SET_CREATE_USER_ERROR";

export const SET_RETRIEVE_POSTS_IGROUP_SUCCESS = "SET_RETRIEVE_POSTS_IGROUP_SUCCESS";
export const SET_RETRIEVE_POSTS_IGROUP_ERROR = "SET_RETRIEVE_POSTS_IGROUP_ERROR";

export const SET_RETRIEVE_EVENTS_IGROUP_SUCCESS = "SET_RETRIEVE_EVENTS_IGROUP_SUCCESS";
export const SET_RETRIEVE_EVENTS_IGROUP_ERROR = "SET_RETRIEVE_EVENTS_IGROUP_ERROR";

export const SET_RETRIEVE_GROUP_INFO_SUCCESS = "SET_RETRIEVE_GROUP_INFO_SUCCESS"
export const SET_RETRIEVE_GROUP_INFO_ERROR = "SET_RETRIEVE_GROUP_INFO_ERROR"

export const SET_POST_GROUP_SUCCESS = "SET_POST_GROUP_SUCCESS";
export const SET_POST_GROUOP_ERROR = "SET_POST_GROUP_ERROR";

export const SET_CREATE_EVENT_SUCCESS = "SET_CREATE_EVENT_SUCCESS";
export const SET_CREATE_EVENT_ERROR = "SET_CREATE_EVENT_ERROR";

export const SET_POST_COMMENT_SUCCESS = "SET_POST_COMMENT_SUCCESS";
export const SET_POST_COMMENT_ERROR = "SET_POST_COMMENT_ERROR";

export const SET_SEND_GROUP_REQ_SUCCESS = "SET_SEND_GROUP_REQ_SUCCESS"
export const SET_SEND_GROUP_REQ_ERROR = "SET_SEND_GROUP_REQ_ERROR"

export const SET_ACCEPT_GROUP_REQ_SUCCESS = "SET_ACCEPT_GROUP_REQ_SUCCESS"
export const SET_ACCEPT_GROUP_REQ_ERROR = "SET_ACCEPT_GROUP_REQ_ERROR"

export const SET_CHANGE_USER_INFO_SUCCESS = "SET_CHANGE_USER_INFO_SUCCESS"
export const SET_CHANGE_USER_INFO_ERROR = "SET_CHANGE_USER_INFO_ERROR"

export const SET_RETRIEVE_USER_INFO_SUCCESS = "SET_RETRIEVE_USER_INFO_SUCCESS"
export const SET_RETRIEVE_USER_INFO_ERROR = "SET_RETRIEVE_USER_INFO_ERROR"

export const SET_GET_USER_POSTS_SUCCESS = "SET_GET_USER_POSTS_SUCCESS"
export const SET_GET_USER_POSTS_ERROR = "SET_GET_USER_POSTS_ERROR"

export const SET_GET_MONTHLY_EVENTS_SUCCESS = "SET_GET_MONTHLY_EVENTS_SUCCESS"
export const SET_GET_MONTHLY_EVENTS_ERROR = "SET_GET_MONTHLY_EVENTS_ERROR"

export const SET_COMMENT_GROUP_POST_SUCCESS = "SET_COMMENT_GROUP_POST_SUCCESS"
export const SET_COMMENT_GROUP_POST_ERROR = "SET_COMMENT_GROUP_POST_ERROR"

// ids for components
export const USERNAME_INPUT = "USERNAME_INPUT";
export const PASSWORD_INPUT = "PASSWORD_INPUT";

export const USERNAME_CREATE_INPUT = "USERNAME__CREATE_INPUT";
export const PASSWORD_CREATE_INPUT = "PASSWORD_CREATE_INPUT";


export const EVENT_NAME_INPUT = "EVENT_NAME_INPUT";
export const EVENT_LOCATION_NAME_INPUT = "EVENT_LOCATION_NAME_INPUT";
export const EVENT_ADDRESS_INPUT = "EVENT_ADDRESS_INPUT";
export const EVENT_POSTALCODE = "EVENT_POSTALCODE";
export const EVENT_CITY = "EVENT_CITY";
export const EVENT_PROVINCE = "EVENT_PROVINCE";
export const EVENT_TIMESTAMP = "EVENT_TS";